recruitment-portal/recruitment-portal/domain/urls.py
from django.urls import path
from .views import list_view, sde_view, finance_view, electronics_view, machine_view, gamedev_view, datascience_view

app_name = 'domain'

urlpatterns = [
    path('', list_view, name='main-domain-view'),
    path('sde/', sde_view, name='sde-domain-view'),
    path('finance/', finance_view, name='finance-domain-view'),
    path('electronics/', electronics_view, name='electronics-domain-view'),
    path('machine/', machine_view, name='machine-domain-view'),
    path('gamedev/', gamedev_view, name='gamedev-domain-view'),
    path('datascience/', datascience_view, name='datascience-domain-view'),
]

recruitment-portal/recruitment-portal/mock/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include
from .views import list_view, dbms_view

app_name = "mock"

urlpatterns = [
    path("", list_view, name="main-mock-view"),
    path('dbms/', dbms_view, name='dbms-mock-view'),
]

recruitment-portal/recruitment-portal/posts/urls.py
from django.urls import path
from .views import list_view,like_unlike_post, PostDeleteView, PostUpdateView, post_create

app_name = 'posts'

urlpatterns = [
    path('', list_view, name='main-post-view'),
    path('all/', post_create, name='add-post-view'),
    path('liked/', like_unlike_post, name='like-post-view'),
    path('<pk>/delete/', PostDeleteView.as_view(), name='post-delete'),
    path('<pk>/update/', PostUpdateView.as_view(), name='post-update'),
]

recruitment-portal/recruitment-portal/webweaver/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.urls.conf import include
from . views import home_view
from posts.views import *

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home_view, name='home-view'),
    # path('accounts/', include('allauth.urls')),
    # path('profiles/', include('profiles.urls', namespace='profiles')),
    path('posts/', include('posts.urls', namespace='posts')),
    path('mock/', include('mock.urls', namespace='mock')),
    path('domain/', include('domain.urls', namespace='domain')),
    path('login/', login_view, name='login-view'),
    path('logout/', logout_view, name='logout'),
    path('webteam/', web_team, name="web_team"),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

recruitment-portal/recruitment-portal/domain/models.py
from django.db import models
from django.core.validators import FileExtensionValidator
from profiles.models import Profile

class Domains(models.Model):
    title = models.CharField(max_length=50)
    content = models.TextField()
    link = models.URLField(max_length=200)
    image = models.ImageField(upload_to='domain', validators=[FileExtensionValidator(['png', 'jpg', 'jpeg'])], blank=True)
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(Profile, on_delete=models.CASCADE, related_name='domain')

    def __str__(self):
        return str(self.content[:500])
    
    def snippet(self):
        return self.content[:100] + "..."

    class Meta:
        ordering = ('-created',)

class Sde(models.Model):
    title = models.CharField(max_length=50)
    content = models.TextField()
    link = models.URLField(max_length=200)
    image = models.ImageField(upload_to='sde', validators=[FileExtensionValidator(['png', 'jpg', 'jpeg'])], blank=True)
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(Profile, on_delete=models.CASCADE, related_name='sde')

    def __str__(self):
        return str(self.content[:500])
    
    def snippet(self):
        return self.content[:100] + "..."

    class Meta:
        ordering = ('-created',)

class Finance(models.Model):
    title = models.CharField(max_length=50)
    content = models.TextField()
    link = models.URLField(max_length=200)
    image = models.ImageField(upload_to='finance', validators=[FileExtensionValidator(['png', 'jpg', 'jpeg'])], blank=True)
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(Profile, on_delete=models.CASCADE, related_name='finance')

    def __str__(self):
        return str(self.content[:500])
    
    def snippet(self):
        return self.content[:100] + "..."

    class Meta:
        ordering = ('-created',)

class Electronics(models.Model):
    title = models.CharField(max_length=50)
    content = models.TextField()
    link = models.URLField(max_length=200)
    image = models.ImageField(upload_to='electronics', validators=[FileExtensionValidator(['png', 'jpg', 'jpeg'])], blank=True)
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(Profile, on_delete=models.CASCADE, related_name='electronics')

    def __str__(self):
        return str(self.content[:500])
    
    def snippet(self):
        return self.content[:100] + "..."

    class Meta:
        ordering = ('-created',)

class Machine(models.Model):
    title = models.CharField(max_length=50)
    content = models.TextField()
    link = models.URLField(max_length=200)
    image = models.ImageField(upload_to='machine', validators=[FileExtensionValidator(['png', 'jpg', 'jpeg'])], blank=True)
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(Profile, on_delete=models.CASCADE, related_name='machine')

    def __str__(self):
        return str(self.content[:500])
    
    def snippet(self):
        return self.content[:100] + "..."

    class Meta:
        ordering = ('-created',)

class Gamedev(models.Model):
    title = models.CharField(max_length=50)
    content = models.TextField()
    link = models.URLField(max_length=200)
    image = models.ImageField(upload_to='gamedev', validators=[FileExtensionValidator(['png', 'jpg', 'jpeg'])], blank=True)
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(Profile, on_delete=models.CASCADE, related_name='gamedev')

    def __str__(self):
        return str(self.content[:500])
    
    def snippet(self):
        return self.content[:100] + "..."

    class Meta:
        ordering = ('-created',)

class Datascience(models.Model):
    title = models.CharField(max_length=50)
    content = models.TextField()
    link = models.URLField(max_length=200)
    image = models.ImageField(upload_to='datascience', validators=[FileExtensionValidator(['png', 'jpg', 'jpeg'])], blank=True)
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(Profile, on_delete=models.CASCADE, related_name='datascience')

    def __str__(self):
        return str(self.content[:500])
    
    def snippet(self):
        return self.content[:100] + "..."

    class Meta:
        ordering = ('-created',)

recruitment-portal/recruitment-portal/domain/views.py
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from .models import Domains, Sde, Finance, Electronics, Machine, Gamedev, Datascience
from profiles.models import Profile
from django.views.generic import UpdateView, DeleteView
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.paginator import Paginator
import requests
from django.contrib.auth.models import auth, User

# @login_required
def list_view(request):
    qs = Domains.objects.all().order_by('created')
    paginator = Paginator(qs, 6)
    page_number = request.GET.get('page')
    qsfinal = paginator.get_page(page_number)
    total_pages = qsfinal.paginator.num_pages

    if request.user.is_authenticated:
        profile = Profile.objects.get(user=request.user)
    else:
        profile = None
    context = {
        'qs': qsfinal,
        'profile': profile,
        'lastpage': total_pages,
        'totalPageList': [n+1 for n in range(total_pages)]
    }

    return render(request, 'domain/main.html', context)

def sde_view(request):
    qs = Sde.objects.all().order_by('created')
    paginator = Paginator(qs, 6)
    page_number = request.GET.get('page')
    qsfinal = paginator.get_page(page_number)
    total_pages = qsfinal.paginator.num_pages

    if request.user.is_authenticated:
        profile = Profile.objects.get(user=request.user)
    else:
        profile = None
    context = {
        'qs': qsfinal,
        'profile': profile,
        'lastpage': total_pages,
        'totalPageList': [n+1 for n in range(total_pages)]
    }

    return render(request, 'domain/sde.html', context)

def finance_view(request):
    qs = Finance.objects.all().order_by('created')
    paginator = Paginator(qs, 6)
    page_number = request.GET.get('page')
    qsfinal = paginator.get_page(page_number)
    total_pages = qsfinal.paginator.num_pages

    if request.user.is_authenticated:
        profile = Profile.objects.get(user=request.user)
    else:
        profile = None
    context = {
        'qs': qsfinal,
        'profile': profile,
        'lastpage': total_pages,
        'totalPageList': [n+1 for n in range(total_pages)]
    }

    return render(request, 'domain/finance.html', context)

def electronics_view(request):
    qs = Electronics.objects.all().order_by('created')
    paginator = Paginator(qs, 6)
    page_number = request.GET.get('page')
    qsfinal = paginator.get_page(page_number)
    total_pages = qsfinal.paginator.num_pages

    if request.user.is_authenticated:
        profile = Profile.objects.get(user=request.user)
    else:
        profile = None
    context = {
        'qs': qsfinal,
        'profile': profile,
        'lastpage': total_pages,
        'totalPageList': [n+1 for n in range(total_pages)]
    }

    return render(request, 'domain/electronics.html', context)

def machine_view(request):
    qs = Machine.objects.all().order_by('created')
    paginator = Paginator(qs, 6)
    page_number = request.GET.get('page')
    qsfinal = paginator.get_page(page_number)
    total_pages = qsfinal.paginator.num_pages

    if request.user.is_authenticated:
        profile = Profile.objects.get(user=request.user)
    else:
        profile = None
    context = {
        'qs': qsfinal,
        'profile': profile,
        'lastpage': total_pages,
        'totalPageList': [n+1 for n in range(total_pages)]
    }

    return render(request, 'domain/machine.html', context)

def gamedev_view(request):
    qs = Gamedev.objects.all().order_by('created')
    paginator = Paginator(qs, 6)
    page_number = request.GET.get('page')
    qsfinal = paginator.get_page(page_number)
    total_pages = qsfinal.paginator.num_pages

    if request.user.is_authenticated:
        profile = Profile.objects.get(user=request.user)
    else:
        profile = None
    context = {
        'qs': qsfinal,
        'profile': profile,
        'lastpage': total_pages,
        'totalPageList': [n+1 for n in range(total_pages)]
    }

    return render(request, 'domain/gamedev.html', context)

def datascience_view(request):
    qs = Datascience.objects.all().order_by('created')
    paginator = Paginator(qs, 6)
    page_number = request.GET.get('page')
    qsfinal = paginator.get_page(page_number)
    total_pages = qsfinal.paginator.num_pages

    if request.user.is_authenticated:
        profile = Profile.objects.get(user=request.user)
    else:
        profile = None
    context = {
        'qs': qsfinal,
        'profile': profile,
        'lastpage': total_pages,
        'totalPageList': [n+1 for n in range(total_pages)]
    }

    return render(request, 'domain/datascience.html', context)

recruitment-portal/recruitment-portal/domain/templates/domain/datascience.html
<!doctype html>
{% load static %}
<html lang="en">
{% url 'home-view' as path_to_home %}
{% url 'posts:main-post-view' as path_to_posts %}
{% url 'posts:add-post-view' as path_to_add_posts %}
{% url 'domain:main-domain-view' as path_to_domain %}
{% url 'mock:main-mock-view' as path_to_mock %}

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
  <link rel="stylesheet" href={% static 'style.css' %}>
  <link rel="stylesheet" href={% static 'modal.css' %}>
  <link rel="stylesheet" href={% static 'index.css' %}>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css"
    integrity="sha512-Fo3rlrZj/k7ujTnHg4CGR2D7kSs0v4LLanw2qksYuRlEzO+tcaEPQogQ0KaoGN26/zrn20ImR1DfuLWnOo7aBA=="
    crossorigin="anonymous" referrerpolicy="no-referrer" />

  <title>Recruitment Portal</title>

  <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
</head>

<body style="background-color:grey;">

  <!-- code for navbar -->
  <div class="nav">
    <input type="checkbox" id="nav-check">
    <div class="nav-header">
      <div class="nav-title">
        <a href="{{path_to_home}}" style="color: white; text-decoration: none; font-weight: 700; font-size: 22px;">
          <img src="{% static 'web-weaver.png' %}" alt="Bootstrap" width="65" class="d-inline-block align-top"
            style="position: fixed;">
        </a>
      </div>
    </div>
    <div class="nav-btn">
      <label for="nav-check">
        <span></span>
        <span></span>
        <span></span>
      </label>
    </div>

    <div class="nav-links">
      <a href="{{path_to_home}}">HOME</a>
      <a href="{{path_to_posts}}">POSTS</a>
      <a href="{{path_to_domain}}">DOMAINS</a>
      <a href="{{path_to_mock}}">MOCK</a>
      {% if request.user.is_authenticated %}
      <a href="{{path_to_add_posts}}">ADD POST</a>
      <a href="{% url 'logout' %}" data-toggle="modal" data-target="#exampleModal">{{request.user.username}}</a>
      {% else %}
      <a href="{% url 'login-view' %}">LOGIN</a>
      <a href="">REGISTER</a>
      {% endif %}
    </div>
  </div>
  <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
    aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <!-- <h5 class="modal-title" id="exampleModalLabel">Modal title</h5> -->
          <!-- <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button> -->
        </div>
        <div class="modal-body">
          LOGOUT <i class="fa fa-lock"></i><br><br>
          <i class="fa fa-question-circle"></i> Are you sure you want to logout?
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          <div class="modal-footer"><a class="btn btn-danger btn-block" href="{% url 'logout' %}">Logout</a></div>
        </div>
      </div>
    </div>
  </div>


  <!-- post -->
  <div class="container-fluid">
    <br>
    <div class="d-flex justify-content-center m-2 post">
      <h1>Data Science</h1>
    </div>
    <div class="container">
      {% if qs %}
      <div class="row">
        {% for article in qs %}
        <div class="col-lg-4 col-md-6 col-sm-12 my-2">
          <div class="col d-flex justify-content-center">
            <div class="card w-75 article">
              <img src={{article.image.url}} style="cursor: pointer" class="card-img-top" alt="..."
                onclick="window.location.href='{{article.link}}'">
              <div class="card-body">
                <h3 class="card-title" style="cursor: pointer;" onclick="window.location.href='{{article.link}}'">
                  {{article.title}}</h3>
                <p class="card-text">{{article.snippet}}</p>
              </div>
            </div>
          </div>
        </div>
        {% endfor %}
      </div>
    </div>
    {% else %}
    <div class="wrapper">
      <div class="d-flex justify-content-center m-2 post" style="margin-bottom:100px">
        <h1>Be the 1st person to Post 😁</h1>
      </div>
    </div>
    <div style="height:380px" class="push"></div>
    {% endif %}
  </div>
  <div class="center">
    <div class="pagination">
      {% if qs.has_previous %}
      <a href="?page=1#" class="pages">First</a>
      <a href="?page={{ qs.previous_page_number }}" class="pages">Previous</a>
      {% endif %}
      {% for n in totalPageList %}
      {% if qs.number == n %}
      <a href="?page={{ n }}" class="active pages">{{ n }}</a>
      {% else %}
      <a href="?page={{ n }}" class="pages">{{ n }}</a>
      {% endif %}
      {% endfor %}
      {% if qs.has_next %}
      <a href="?page={{ qs.next_page_number }}" class="pages">Next</a>
      <a href="?page={{ lastpage }}" class="pages">Last</a>
      {% endif %}
    </div>
  </div>
  <footer>
    <!-- <div class="leftieee">
          © PICT IEEE Student Branch
        </div> -->
    <div class="middleieee">
      Internship Portal | Made with ❤️ by <a href="{% url 'web_team' %}" style="text-decoration:none; color: #2691D9;">Web
        Team</a>
    </div>
    <!-- <div class="lastieee">
          <div class = "social-links">
    
            <a href = "https://www.linkedin.com/company/pisbieee"><i class = "fab fa-linkedin-in"></i></a>
            <a href = "https://www.youtube.com/c/PICTIEEEStudentBranch"><i class = "fab fa-youtube"></i></a>
            <a href = "https://instagram.com/pictieee?utm_medium=copy_link"><i class = "fab fa-instagram"></i></a>
      
          </div>
        </div> -->

  </footer>
  <!-- Optional JavaScript; choose one of the two! -->

  <!-- Option 1: Bootstrap Bundle with Popper -->
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous">
  </script>

  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"
    integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous">
  </script>

  <!-- Option 2: Separate Popper and Bootstrap JS -->
  <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
    -->
</body>


</html>

recruitment-portal/recruitment-portal/domain/templates/domain/electronics.html
<!doctype html>
{% load static %}
<html lang="en">
{% url 'home-view' as path_to_home %}
{% url 'posts:main-post-view' as path_to_posts %}
{% url 'posts:add-post-view' as path_to_add_posts %}
{% url 'domain:main-domain-view' as path_to_domain %}
{% url 'mock:main-mock-view' as path_to_mock %}

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
  <link rel="stylesheet" href={% static 'style.css' %}>
  <link rel="stylesheet" href={% static 'modal.css' %}>
  <link rel="stylesheet" href={% static 'index.css' %}>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css"
    integrity="sha512-Fo3rlrZj/k7ujTnHg4CGR2D7kSs0v4LLanw2qksYuRlEzO+tcaEPQogQ0KaoGN26/zrn20ImR1DfuLWnOo7aBA=="
    crossorigin="anonymous" referrerpolicy="no-referrer" />

  <title>Recruitment Portal</title>

  <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
</head>

<body style="background-color:grey;">

  <!-- code for navbar -->
  <div class="nav">
    <input type="checkbox" id="nav-check">
    <div class="nav-header">
      <div class="nav-title">
        <a href="{{path_to_home}}" style="color: white; text-decoration: none; font-weight: 700; font-size: 22px;">
          <img src="{% static 'web-weaver.png' %}" alt="Bootstrap" width="65" class="d-inline-block align-top"
            style="position: fixed;">
        </a>
      </div>
    </div>
    <div class="nav-btn">
      <label for="nav-check">
        <span></span>
        <span></span>
        <span></span>
      </label>
    </div>

    <div class="nav-links">
      <a href="{{path_to_home}}">HOME</a>
      <a href="{{path_to_posts}}">POSTS</a>
      <a href="{{path_to_domain}}">DOMAINS</a>
      <a href="{{path_to_mock}}">MOCK</a>
      {% if request.user.is_authenticated %}
      <a href="{{path_to_add_posts}}">ADD POST</a>
      <a href="{% url 'logout' %}" data-toggle="modal" data-target="#exampleModal">{{request.user.username}}</a>
      {% else %}
      <a href="{% url 'login-view' %}">LOGIN</a>
      <a href="">REGISTER</a>
      {% endif %}
    </div>
  </div>
  <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
    aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <!-- <h5 class="modal-title" id="exampleModalLabel">Modal title</h5> -->
          <!-- <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button> -->
        </div>
        <div class="modal-body">
          LOGOUT <i class="fa fa-lock"></i><br><br>
          <i class="fa fa-question-circle"></i> Are you sure you want to logout?
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          <div class="modal-footer"><a class="btn btn-danger btn-block" href="{% url 'logout' %}">Logout</a></div>
        </div>
      </div>
    </div>
  </div>


  <!-- post -->
  <div class="container-fluid">
    <br>
    <div class="d-flex justify-content-center m-2 post">
      <h1>Electronics</h1>
    </div>
    <div class="container">
      {% if qs %}
      <div class="row">
        {% for article in qs %}
        <div class="col-lg-4 col-md-6 col-sm-12 my-2">
          <div class="col d-flex justify-content-center">
            <div class="card w-75 article">
              <img src={{article.image.url}} style="cursor: pointer" class="card-img-top" alt="..."
                onclick="window.location.href='{{article.link}}'">
              <div class="card-body">
                <h3 class="card-title" style="cursor: pointer;" onclick="window.location.href='{{article.link}}'">
                  {{article.title}}</h3>
                <p class="card-text">{{article.snippet}}</p>
              </div>
            </div>
          </div>
        </div>
        {% endfor %}
      </div>
    </div>
    {% else %}
    <div class="wrapper">
      <div class="d-flex justify-content-center m-2 post" style="margin-bottom:100px">
        <h1>Be the 1st person to Post 😁</h1>
      </div>
    </div>
    <div style="height:380px" class="push"></div>
    {% endif %}
  </div>
  <div class="center">
    <div class="pagination">
      {% if qs.has_previous %}
      <a href="?page=1#" class="pages">First</a>
      <a href="?page={{ qs.previous_page_number }}" class="pages">Previous</a>
      {% endif %}
      {% for n in totalPageList %}
      {% if qs.number == n %}
      <a href="?page={{ n }}" class="active pages">{{ n }}</a>
      {% else %}
      <a href="?page={{ n }}" class="pages">{{ n }}</a>
      {% endif %}
      {% endfor %}
      {% if qs.has_next %}
      <a href="?page={{ qs.next_page_number }}" class="pages">Next</a>
      <a href="?page={{ lastpage }}" class="pages">Last</a>
      {% endif %}
    </div>
  </div>
  <footer>
    <!-- <div class="leftieee">
          © PICT IEEE Student Branch
        </div> -->
    <div class="middleieee">
      Internship Portal | Made with ❤️ by <a href="{% url 'web_team' %}" style="text-decoration:none; color: #2691D9;">Web
        Team</a>
    </div>
    <!-- <div class="lastieee">
          <div class = "social-links">
    
            <a href = "https://www.linkedin.com/company/pisbieee"><i class = "fab fa-linkedin-in"></i></a>
            <a href = "https://www.youtube.com/c/PICTIEEEStudentBranch"><i class = "fab fa-youtube"></i></a>
            <a href = "https://instagram.com/pictieee?utm_medium=copy_link"><i class = "fab fa-instagram"></i></a>
      
          </div>
        </div> -->

  </footer>
  <!-- Optional JavaScript; choose one of the two! -->

  <!-- Option 1: Bootstrap Bundle with Popper -->
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous">
  </script>

  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"
    integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous">
  </script>

  <!-- Option 2: Separate Popper and Bootstrap JS -->
  <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
    -->
</body>


</html>