recruitment-portal/recruitment-portal/domain/urls.py
from django.urls import path
from .views import list_view, sde_view, finance_view, electronics_view, machine_view, gamedev_view, datascience_view

app_name = 'domain'

urlpatterns = [
    path('', list_view, name='main-domain-view'),
    path('sde/', sde_view, name='sde-domain-view'),
    path('finance/', finance_view, name='finance-domain-view'),
    path('electronics/', electronics_view, name='electronics-domain-view'),
    path('machine/', machine_view, name='machine-domain-view'),
    path('gamedev/', gamedev_view, name='gamedev-domain-view'),
    path('datascience/', datascience_view, name='datascience-domain-view'),
]

recruitment-portal/recruitment-portal/mock/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include
from .views import list_view, dbms_view

app_name = "mock"

urlpatterns = [
    path("", list_view, name="main-mock-view"),
    path('dbms/', dbms_view, name='dbms-mock-view'),
]

recruitment-portal/recruitment-portal/posts/urls.py
from django.urls import path
from .views import list_view,like_unlike_post, PostDeleteView, PostUpdateView, post_create

app_name = 'posts'

urlpatterns = [
    path('', list_view, name='main-post-view'),
    path('all/', post_create, name='add-post-view'),
    path('liked/', like_unlike_post, name='like-post-view'),
    path('<pk>/delete/', PostDeleteView.as_view(), name='post-delete'),
    path('<pk>/update/', PostUpdateView.as_view(), name='post-update'),
]

recruitment-portal/recruitment-portal/webweaver/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.urls.conf import include
from . views import home_view
from posts.views import *

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home_view, name='home-view'),
    # path('accounts/', include('allauth.urls')),
    # path('profiles/', include('profiles.urls', namespace='profiles')),
    path('posts/', include('posts.urls', namespace='posts')),
    path('mock/', include('mock.urls', namespace='mock')),
    path('domain/', include('domain.urls', namespace='domain')),
    path('login/', login_view, name='login-view'),
    path('logout/', logout_view, name='logout'),
    path('webteam/', web_team, name="web_team"),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

recruitment-portal/recruitment-portal/posts/models.py
from django.db import models
from django.core.validators import FileExtensionValidator
from profiles.models import Profile

class Post(models.Model):
    title = models.CharField(max_length=50)
    content = models.TextField()
    link = models.URLField(max_length=200)
    image = models.ImageField(upload_to='posts', validators=[FileExtensionValidator(['png', 'jpg', 'jpeg'])], blank=True)
    liked = models.ManyToManyField(Profile, blank=True, related_name='likes')
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(Profile, on_delete=models.CASCADE, related_name='posts')

    def __str__(self):
        return str(self.content[:500])

    def num_likes(self):
        return self.liked.all().count()

    def num_comments(self):
        return self.comment_set.all().count()
    
    def snippet(self):
        return self.content

    class Meta:
        ordering = ('-created',)


LIKE_CHOICES = (
    ('Like', 'Like'),
    ('Unlike', 'Unlike'),
)

class Like(models.Model): 
    user = models.ForeignKey(Profile, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    value = models.CharField(choices=LIKE_CHOICES, max_length=8)
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return f"{self.user}-{self.post}-{self.value}"

recruitment-portal/recruitment-portal/posts/forms.py
from django import forms
from .models import Post

class PostModelForm(forms.ModelForm):
    content = forms.CharField(widget=forms.Textarea(attrs={'rows':2}))
    class Meta:
        model = Post
        fields = ('title', 'content', 'link', 'image')

recruitment-portal/recruitment-portal/posts/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from .models import Post, Like
from profiles.models import Profile
from .forms import PostModelForm
from django.views.generic import UpdateView, DeleteView
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.paginator import Paginator
import requests
from django.contrib.auth.models import auth, User
from gtts import gTTS
# from gTTS.templatetags.gTTS import say

# @login_required
def list_view(request):
    qs = Post.objects.all().order_by('created')
    paginator = Paginator(qs, 6)
    page_number = request.GET.get('page')
    qsfinal = paginator.get_page(page_number)
    total_pages = qsfinal.paginator.num_pages

    if request.user.is_authenticated:
        profile = Profile.objects.get(user=request.user)
    else:
        profile = None
    context = {
        'qs': qsfinal,
        'profile': profile,
        'lastpage': total_pages,
        'totalPageList': [n+1 for n in range(total_pages)]
    }

    return render(request, 'posts/main.html', context)

@login_required
def post_create(request):
    qs = Post.objects.all()
    profile = Profile.objects.get(user=request.user)
    post_added = False

    if request.method == 'POST':
        # print(request.FILES)
        data = request.POST
        dataImage = request.FILES
        title = data['title']
        link = data['link']
        description = data['description']
        image = dataImage['picture']
        p_form = Post(title=title,content=description,link=link,image=image,author=profile)
        p_form.save()
        p_form = PostModelForm()
        post_added = True

    context = {
        'qs': qs,
        'profile': profile,
        'post_added': post_added,
    }

    return render(request, 'posts/addposts.html', context)

@login_required
def like_unlike_post(request):
    user = request.user
    if request.method == 'POST':
        post_id = request.POST.get('post_id')
        post_obj = Post.objects.get(id=post_id)
        profile = Profile.objects.get(user=user)

        if profile in post_obj.liked.all():
            post_obj.liked.remove(profile)
        else:
            post_obj.liked.add(profile)

        like, created = Like.objects.get_or_create(user=profile, post_id=post_id)

        if not created: # created is a bool, if already that Like object is there, created = false(i.e we haven't created, just GET that Like object)
            if like.value=='Like':
                like.value='Unlike'
            else:
                like.value='Like'
        else:
            like.value='Like'

        post_obj.save()
        like.save()

        return redirect('posts:main-post-view')

class PostDeleteView(LoginRequiredMixin, DeleteView):
    model = Post
    template_name = 'posts/confirm_del.html'
    success_url = reverse_lazy('posts:main-post-view')
    # success_url = '/posts/'

    def get_object(self, *args, **kwargs):
        pk = self.kwargs.get('pk')
        obj = Post.objects.get(pk=pk)
        if not obj.author.user == self.request.user:
            messages.warning(self.request, 'You need to be the author of the post in order to delete it')
        return obj

def index(request):
    obj1 = "Text From Views"
    return render(request, 'posts/index.html', {'obj1':obj1})

class PostUpdateView(LoginRequiredMixin, UpdateView):
    form_class = PostModelForm
    model = Post
    template_name = 'posts/update.html'
    success_url = reverse_lazy('posts:main-post-view')

    def form_valid(self, form):
        profile = Profile.objects.get(user=self.request.user)
        if form.instance.author == profile:
            return super().form_valid(form)
        else:
            form.add_error(None, "You need to be the author of the post in order to update it")
            return super().form_invalid(form)

def login_view(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        url = "https://backend.credenz.in/api/check_user/"
        payload={'username': username,
                'password': password,
                'event': 'Webweaver'
                }
        response = requests.request("POST", url, data=payload)
        if response.status_code == 200:
            data = response.json()
            print(data)
            print("Senior : ",data['senior'])
            print("Bool Check : ",bool(User.objects.filter(username=username).exists()))
            if not(User.objects.filter(username=username).exists()):
                user = User.objects.create_user(username=username, password=password, email="dummy@gmail.com", first_name="dummyfname", last_name="dummylname")
                user.save()
        else:
            url = "https://registrations.credenz.in/api/event_players/check_user/"
            payload={'username': username,
                    'password': password,
                    'event': 'Web Weaver'
                }
            response = requests.request("POST", url, data=payload)
            if response.status_code == 200:
                data = response.json()
                print("Senior : ",data['senior'])
                print("Bool Check : ",bool(User.objects.filter(username=username).exists()))
                if not(User.objects.filter(username=username).exists()):
                    user = User.objects.create_user(username=username, password=password, email="dummy@gmail.com", first_name="dummyfname", last_name="dummylname")
                    user.save()
            else:
                # messages.error(request,"User does exist")
                # return render(request, 'posts/login.html', {'title': 'Login'})
                return render(request, 'posts/login.html', context={'data': {
                'message': 'Users does not exist'
            }})
        # print('Username : {}\nPassword : {}'.format(username, password))
        if User.objects.filter(username=username).exists():
            user = authenticate(username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect('/')
        else:
            return render(request, 'posts/login.html', context={'data': {
                'message': 'Wrong Credentials'
            }})
    elif request.method == 'GET':
        return render(request, 'posts/login.html')

def logout_view(request):
    logout(request)
    return redirect('/')

def web_team(request):
    return render(request, 'posts/webteam.html')

recruitment-portal/recruitment-portal/posts/templates/posts/confirm_del.html
<!DOCTYPE html>
{% load static %}
{% url 'home-view' as path_to_home %}
{% url 'posts:main-post-view' as path_to_posts %}
{% url 'posts:add-post-view' as path_to_add_posts %}
{% url 'domain:main-domain-view' as path_to_domain %}
{% url 'mock:main-mock-view' as path_to_mock %}
<html>

<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>Recruitment Portal</title>
  <link rel="shortcut icon" type="image/png" href={% static 'pisb-favicon.png' %}>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <!-- Font awesome icon -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
    integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/css/all.min.css"
    integrity="sha512-+4zCK9k+qNFUR5X+cKL9EIR+ZOhtIloNl9GIKS57V1MyNsYpYcUrUeQc9vNfzsWfV28IaLL3i96P9sdNyeRssA=="
    crossorigin="anonymous" />
  <!-- <link rel="stylesheet" href="/css/home.css"> -->
  <link rel="stylesheet" href={% static 'index.css' %}>
  <link rel="stylesheet" href={% static 'addpost.css' %}>
  <link rel="stylesheet" href={% static 'style.css' %}>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.2/css/all.min.css" />
  <script src="https://kit.fontawesome.com/64d58efce2.js" crossorigin="anonymous"></script>
</head>

<body>

  <div class="nav">
    <input type="checkbox" id="nav-check">
    <div class="nav-header">
      <div class="nav-title">
        <a href="{{path_to_home}}" style="color: white; text-decoration: none; font-weight: 700; font-size: 22px;">
        </a>
      </div>
    </div>
    <div class="nav-btn">
      <label for="nav-check">
        <span></span>
        <span></span>
        <span></span>
      </label>
    </div>

    <div class="nav-links">
      <a href="{{path_to_home}}">HOME</a>
      <a href="{{path_to_posts}}">POSTS</a>
      <a href="{{path_to_domain}}">DOMAINS</a>
      <a href="{{path_to_mock}}">MOCK</a>
      {% if request.user.is_authenticated %}
      <a href="{{path_to_add_posts}}">ADD POST</a>
      <a href="#" data-toggle="modal" data-target="#exampleModal">{{request.user}}</a>
      {% else %}
      <a href="{% url 'login-view' %}">LOGIN</a>
      <a href="">REGISTER</a>
      {% endif %}
    </div>
  </div>

  <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
    aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          LOGOUT <i class="fa fa-lock"></i><br><br>
          <i class="fa fa-question-circle"></i> Are you sure you want to logout?
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          <div class="modal-footer"><a class="btn btn-danger btn-block" href="{% url 'logout' %}">Logout</a></div>
        </div>
      </div>
    </div>
  </div>

  {% if messages %}
  {% for message in messages %}
  {% if 'warning' in message.tags %}
  <div class='ui negative message'>
    <div class="header">
      {{message}}
    </div>
  </div>
  {% endif %}
  {% endfor %}
  {% endif %}

  {% if not messages %}
  <div class="ui segment">
    <h3 style="color:white;font-family: 'Poppins', sans-serif;">Delete post?</h3>
    <form action="" method="POST">
      {% csrf_token %}
      <p style="color:white;font-family: 'Poppins', sans-serif;">Are you sure you want to delete the post?</p>
      <button style="cursor: pointer;border-radius: 5px;
                padding: 10px 10px;font-size: 15px;font-family: 'Poppins', sans-serif;" type='submit'
        class="ui button primary">Delete</button>
    </form>
  </div>
  {% endif %}
  <div style="height:450px" class="push"></div>

  <!-- footer -->
  <footer>
    <!-- <div class="leftieee">
        © PICT IEEE Student Branch
      </div> -->
    <div class="middleieee">
      &copy; Internship Portal | Made with ❤️ by <a href="{% url 'web_team' %}">Web Team</a>
    </div>
    <!-- <div class="lastieee">
        <div class = "social-links">
  
          <a href = "https://www.linkedin.com/company/pisbieee"><i class = "fab fa-linkedin-in"></i></a>
          <a href = "https://www.youtube.com/c/PICTIEEEStudentBranch"><i class = "fab fa-youtube"></i></a>
          <a href = "https://instagram.com/pictieee?utm_medium=copy_link"><i class = "fab fa-instagram"></i></a>
    
        </div>
      </div> -->

  </footer>
  <!-- end of footer -->


</body>

</html>

recruitment-portal/recruitment-portal/posts/templates/posts/index.html
{% load gTTS %}

<audio
    src="{% say 'en-us' obj %}"
    controls
></audio>

recruitment-portal/recruitment-portal/posts/templates/posts/main.html
<!doctype html>
{% load static %}
<html lang="en">
{% url 'home-view' as path_to_home %}
{% url 'posts:main-post-view' as path_to_posts %}
{% url 'posts:add-post-view' as path_to_add_posts %}
{% url 'domain:main-domain-view' as path_to_domain %}
{% url 'mock:main-mock-view' as path_to_mock %}

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
  <link rel="stylesheet" href={% static 'style.css' %}>
  <link rel="stylesheet" href={% static 'modal.css' %}>
  <link rel="stylesheet" href={% static 'index.css' %}>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css"
    integrity="sha512-Fo3rlrZj/k7ujTnHg4CGR2D7kSs0v4LLanw2qksYuRlEzO+tcaEPQogQ0KaoGN26/zrn20ImR1DfuLWnOo7aBA=="
    crossorigin="anonymous" referrerpolicy="no-referrer" />

  <title>Recruitment Portal</title>

  <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
</head>

<body style="background-color:grey;">

  <!-- code for navbar -->
  <div class="nav">
    <input type="checkbox" id="nav-check">
    <div class="nav-header">
      <div class="nav-title">
        <a href="{{path_to_home}}" style="color: white; text-decoration: none; font-weight: 700; font-size: 22px;">
          <img src="{% static 'web-weaver.png' %}" alt="Bootstrap" width="65" class="d-inline-block align-top"
            style="position: fixed;">
        </a>
      </div>
    </div>
    <div class="nav-btn">
      <label for="nav-check">
        <span></span>
        <span></span>
        <span></span>
      </label>
    </div>

    <div class="nav-links">
      <a href="{{path_to_home}}">HOME</a>
      <a href="{{path_to_posts}}">POSTS</a>
      <a href="{{path_to_domain}}">DOMAINS</a>
      <a href="{{path_to_mock}}">MOCK</a>
      {% if request.user.is_authenticated %}
      <a href="{{path_to_add_posts}}">ADD POST</a>
      <a href="{% url 'logout' %}" data-toggle="modal" data-target="#exampleModal">{{request.user.username}}</a>
      {% else %}
      <a href="{% url 'login-view' %}">LOGIN</a>
      <a href="">REGISTER</a>
      {% endif %}
    </div>
  </div>
  <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
    aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <!-- <h5 class="modal-title" id="exampleModalLabel">Modal title</h5> -->
          <!-- <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button> -->
        </div>
        <div class="modal-body">
          LOGOUT <i class="fa fa-lock"></i><br><br>
          <i class="fa fa-question-circle"></i> Are you sure you want to logout?
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          <div class="modal-footer"><a class="btn btn-danger btn-block" href="{% url 'logout' %}">Logout</a></div>
        </div>
      </div>
    </div>
  </div>


  <!-- post -->
  <div class="container-fluid">
    <br>
    <div class="d-flex justify-content-center m-2 post">
      <h1>POSTS</h1>
    </div>
    
    <div class="container">
      {% if qs %}
      <div class="row">
        {% for article in qs %}
        <div class="col-lg-4 col-md-6 col-sm-12 my-2">
          <div class="col d-flex justify-content-center">
            <div class="card w-75 article">
              <img src={{article.image.url}} style="cursor: pointer" class="card-img-top" alt="..."
                onclick="window.location.href='{{article.link}}'">
              <div class="card-body">
                <h3 class="card-title" style="cursor: pointer;" onclick="window.location.href='{{article.link}}'">
                  {{article.title}}</h3>
                <p class="card-text">{{article.snippet}}</p>
                <!-- <a href="#" class="btn btn-primary">Go somewhere</a> -->
                <p class="text-end">-{{article.author.user}}</p>
                <div class="row">
                  {% if request.user == article.author.user %}
                  <a class="text-end" style="font-size:25px;" href="{% url 'posts:post-delete' article.pk %}"><button
                      style="background:transparent; border:none;"><i style="color:#fff"
                        class="fa-solid fa-trash-can"></i></button></a>
                  {% endif %}
                </div>
                <form action="{% url 'posts:like-post-view' %}" method="POST" class='like-form' id='{{article.id}}'>
                  {% csrf_token %}
                  <input type="hidden" name="post_id" value={{article.id}}>
                  <button style="background:transparent; border:none;" type="submit"
                    class="ui button like-btn{{article.id}}">
                    {% if profile not in article.liked.all %}
                    🧑‍💻
                    {% else %}
                    ✅
                    {% endif %}
                  </button>

                  <span class="like-count{{article.id}}"> {{article.num_likes}} </span>
                  <span>Registrations</span>
                </form>
                <!-- <span>{{article.num_likes}}</span> -->
              </div>
            </div>
          </div>
        </div>
        {% endfor %}
      </div>
    </div>
    {% else %}
    <div class="wrapper">
      <div class="d-flex justify-content-center m-2 post" style="margin-bottom:100px">
        <h1>Be the 1st person to Post 😁</h1>
      </div>
    </div>
    <div style="height:380px" class="push"></div>
    {% endif %}
  </div>

  <div class="container">
    <form action="" method="post">
        {% csrf_token %}
        <label for="exampleFormControlInput1" class="form-label">Language</label>
        <select class="form-select form-select-lg mb-3" aria-label=".form-select-lg example" name="lang">
            <option value="en">English</option>
            <option value="hi">Hindi</option>
            <option value="fr">French</option>
            <option value="zh-TW">Mandarin (Taiwan)</option>
            <option value="zh-CN">Mandarin (China Mainland)</option>
            <option value="pt">Portuguese</option>
            <option value="es">Spanish</option>
        </select>

        <label for="exampleFormControlInput1" class="form-label">Country</label>
        <select class="form-select form-select-lg mb-3" aria-label=".form-select-lg example" name='tdl'>
            <option value="com.au">Australia</option>
            <option value="co.uk">United Kingdom</option>
            <option value="com">United States</option>
            <option value="ca">Canada</option>
            <option value="co.in">India</option>
            <option value="ie">Ireland</option>
            <option value="co.za">South Africa</option>
            <option value="ca">Canada</option>
            <option value="fr">France</option>
            <option value="com.br">Brazil</option>
            <option value="pt">Portugal</option>
            <option value="com.mx">Mexico</option>
            <option value="com.mx">Spain</option>
            <option value="com">United States</option>
        </select>

        <div class="mb-3">
            <textarea class="form-control" id="text_area" rows="12" name="text" required  placeholder="Write Something here..."></textarea>
        </div>

        <div class="col-auto">
           <input type="submit" class="btn btn-success" value="Generate">
        </div>
    </form>
</div>

  <div class="center">
    <div class="pagination">
      {% if qs.has_previous %}
      <a href="?page=1#" class="pages">First</a>
      <a href="?page={{ qs.previous_page_number }}" class="pages">Previous</a>
      {% endif %}
      {% for n in totalPageList %}
      {% if qs.number == n %}
      <a href="?page={{ n }}" class="active pages">{{ n }}</a>
      {% else %}
      <a href="?page={{ n }}" class="pages">{{ n }}</a>
      {% endif %}
      {% endfor %}
      {% if qs.has_next %}
      <a href="?page={{ qs.next_page_number }}" class="pages">Next</a>
      <a href="?page={{ lastpage }}" class="pages">Last</a>
      {% endif %}
    </div>
  </div>
  <footer>
    <!-- <div class="leftieee">
          © PICT IEEE Student Branch
        </div> -->
    <div class="middleieee">
      Internship Portal | Made with ❤️ by <a href="{% url 'web_team' %}"
        style="text-decoration:none; color: #2691D9;">Web
        Team</a>
    </div>
    <!-- <div class="lastieee">
          <div class = "social-links">
    
            <a href = "https://www.linkedin.com/company/pisbieee"><i class = "fab fa-linkedin-in"></i></a>
            <a href = "https://www.youtube.com/c/PICTIEEEStudentBranch"><i class = "fab fa-youtube"></i></a>
            <a href = "https://instagram.com/pictieee?utm_medium=copy_link"><i class = "fab fa-instagram"></i></a>
      
          </div>
        </div> -->

  </footer>
  <!-- Optional JavaScript; choose one of the two! -->

  <!-- Option 1: Bootstrap Bundle with Popper -->
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous">
  </script>

  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"
    integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous">
  </script>

  <!-- Option 2: Separate Popper and Bootstrap JS -->
  <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
    -->
  <script>
    $(document).ready(function () {

      $('.like-form').submit(function (e) {
        e.preventDefault()
        console.log("works");
        const post_id = $(this).attr('id')

        const likeText = $(`.like-btn${post_id}`).text()
        const trim = $.trim(likeText)

        const url = $(this).attr('action')

        let res;
        const likes = $(`.like-count${post_id}`).text()
        const trimCount = parseInt(likes)

        $.ajax({
          type: 'POST',
          url: url,
          data: {
            'csrfmiddlewaretoken': $('input[name=csrfmiddlewaretoken]').val(),
            'post_id': post_id,
          },
          success: function (response) {
            if (trim === '🧑‍💻') {
              $(`.like-btn${post_id}`).text('✅')
              res = trimCount + 1
            } else {
              $(`.like-btn${post_id}`).text('🧑‍💻')
              res = trimCount - 1
            }

            $(`.like-count${post_id}`).text(res)
          },
          error: function (response) {
            console.log('error', response)
          }
        })

      })
    });
  </script>
</body>


</html>